In [1]:
from koRKut_tokenizer import koRKutTokenizer

korkut_tokenizer = koRKutTokenizer(vocab_file="tokenizer.json", emptiness=61)

In [2]:
with open("text.txt", "r") as f:
    text = f.read()

text

"Saygıdeğer iş dünyası ve değerli paydaşlar,\n\nTürkiye'nin büyük kültür mirası ve zengin tarihî dokusu, özgürlük, sevgi ve kardeşlik değerleriyle bütünleşerek güçlü bir gelecek inşa etmektedir. İnsanların bilgi, bilim ve teknolojiyle donanması, modern dünyanın değişim ve gelişim sürecinde başarıyı getirecek temel unsurlardır. Eğitim ve çalışma azmiyle harmanlanan bu süreç, yaşam kalitesini yükseltmekte, mutluluk ve barış ortamını desteklemektedir. Gelenek ve modernliği dengede tutan, dostluk ve umutla örülü bu yol, ülkemizi daha güzel yarınlara taşımaktadır.\n\nSaygıdeğer iş dünyası ve değerli paydaşlar,\n\nTürkiye'nin büyük kültür mirası ve zengin tarihî dokusu, özgürlük, sevgi ve kardeşlik değerleriyle bütünleşerek güçlü bir gelecek inşa etmektedir. İnsanların bilgi, bilim ve teknolojiyle donanması, modern dünyanın değişim ve gelişim sürecinde başarıyı getirecek temel unsurlardır. Eğitim ve çalışma azmiyle harmanlanan bu süreç, yaşam kalitesini yükseltmekte, mutluluk ve barış ortamı

In [3]:
token_ids = korkut_tokenizer.encode(text)
token_ids

tensor([70, 70, 70,  ..., 70, 70, 70])

In [4]:
context_length = 12
stride = 2

In [5]:
from koRKut_model import koRKutModel

korkut_model = koRKutModel(vocab_size=len(korkut_tokenizer.vocab), embedding_dim=32, num_heads=4, context_length=context_length, num_layers=8)

In [6]:
from koRKut_dataloader import TextDataset
korkut_dataloader = TextDataset(token_ids=token_ids, context_length=context_length, stride=stride)
korkut_dataloader.inputs[0], korkut_dataloader.targets[0]

(tensor([70, 70, 70, 70, 70,  6, 70, 70, 70, 61, 70, 70]),
 tensor([70, 70, 70, 70,  6, 70, 70, 70, 61, 70, 70, 61]))

In [7]:
import torch
optimizer = torch.optim.Adam(korkut_model.parameters(), lr=1e-3)
loss_fn = torch.nn.CrossEntropyLoss()

In [8]:
import torch

torch.cuda.is_available()

True

In [9]:
from koRKut_train import koRKutTrain

trainer = koRKutTrain(korkut_model, korkut_dataloader, optimizer, loss_fn)
trainer.train(epochs=10)

[Epoch 1] Loss: 1.2447
[Epoch 2] Loss: 1.0558
[Epoch 3] Loss: 1.1353
[Epoch 4] Loss: 1.0742
[Epoch 5] Loss: 1.1157
[Epoch 6] Loss: 1.1365
[Epoch 7] Loss: 1.1568
[Epoch 8] Loss: 1.0969
[Epoch 9] Loss: 1.1362
[Epoch 10] Loss: 1.1130


In [13]:
# the capital of the united states is not london.
sentence = "sevgi ve kardeşlik değerleriyle"
sentence_token = korkut_tokenizer.encode(sentence)
sentence_token

tensor([38, 61,  1, 61, 41, 61,  6, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70])

In [14]:
korkut_model.eval()
out = korkut_model.generate(sentence_token, max_new_tokens=5)
out

[38,
 61,
 1,
 61,
 41,
 61,
 6,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 61,
 70,
 35]

In [12]:
korkut_tokenizer.decode(out)

'<unk><unk><unk>dostluk<unk><unk><unk><unk><unk><unk><unk>dostluk<unk><unk>dostluk<unk><unk><unk><unk>türkiye<unk>sevgi<unk>'