In [1]:
from koRKut_tokenizer import koRKutTokenizer

korkut_tokenizer = koRKutTokenizer(vocab_file="tokenizer.json", emptiness=2)

metin = "Merhaba, nasılsınız?"

metin_token = korkut_tokenizer.encode(metin)
metin_token


tensor([ 1336, 11469,    67,     2, 26874,   240, 10975,   240,    80,   240,
           92])

In [2]:
korkut_tokenizer.encode(" ")

tensor([])

In [19]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel

model_name = "cenkersisman/gpt2-turkish-128-token"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)

/home/emin/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [20]:
device = "cuda"

In [21]:
with open("text.txt", "r") as f:
    text = f.read()

text

'Derin öğrenme, günümüz teknoloji dünyasında merkezi bir rol oynamaktadır ve derin öğrenme, veriden öğrenme kavramını temelden dönüştüren bir yaklaşımdır. Derin öğrenme, verilerden öğrenmeyi mümkün kılan, çok katmanlı sinir ağları üzerine kurulu bir yapay zeka yöntemidir ve derin öğrenme, verilerin iç yapısını analiz ederek soyut temsiller oluşturma kabiliyeti ile öne çıkmaktadır. Derin öğrenme, yalnızca yüzeysel bilgileri değil, derin ilişkileri, karmaşık örüntüleri ve sezgisel bağlantıları da yakalayabilen bir öğrenme biçimidir. Derin öğrenme, veriye dayalı karar verme süreçlerinde insan benzeri performans gösteren sistemler inşa etmeyi mümkün kılar ve derin öğrenme, bu bağlamda makinelere yalnızca veri değil, aynı zamanda bağlam, örüntü ve yorumlama becerisi de kazandırır. Derin öğrenme, yüksek hacimli veri kümeleriyle çalışarak öğrenen, kendini geliştiren ve zamanla daha doğru sonuçlar üretebilen sistemlerin temelini oluşturur. Derin öğrenme, insan beyninin öğrenme mekanizmalarını 

In [25]:
token_ids = tokenizer.encode(text)
token_ids

Token indices sequence length is longer than the specified maximum sequence length for this model (7027 > 1024). Running this sequence through the model will result in indexing errors


[36,
 264,
 263,
 221,
 1019,
 286,
 12,
 221,
 6291,
 221,
 2286,
 221,
 650,
 4033,
 221,
 8388,
 221,
 294,
 221,
 744,
 221,
 1069,
 21809,
 221,
 282,
 221,
 3065,
 221,
 1019,
 286,
 12,
 221,
 878,
 314,
 221,
 1019,
 286,
 221,
 2736,
 9325,
 221,
 1556,
 314,
 221,
 1874,
 382,
 265,
 221,
 294,
 221,
 4225,
 315,
 14,
 221,
 36,
 264,
 263,
 221,
 1019,
 286,
 12,
 221,
 878,
 9369,
 221,
 1019,
 286,
 529,
 221,
 3356,
 221,
 356,
 347,
 12,
 221,
 560,
 221,
 5645,
 305,
 221,
 4405,
 221,
 613,
 2664,
 221,
 588,
 628,
 221,
 6830,
 221,
 294,
 221,
 6176,
 221,
 6724,
 221,
 579,
 45682,
 317,
 221,
 282,
 221,
 3065,
 221,
 1019,
 286,
 12,
 221,
 878,
 2617,
 221,
 374,
 221,
 949,
 17987,
 221,
 3410,
 221,
 6255,
 331,
 221,
 8456,
 221,
 1611,
 289,
 221,
 42921,
 278,
 221,
 10171,
 73,
 221,
 319,
 221,
 528,
 221,
 491,
 21809,
 14,
 221,
 36,
 264,
 263,
 221,
 1019,
 286,
 12,
 221,
 2647,
 221,
 2725,
 521,
 221,
 351,
 1465,
 221,
 1462,
 12,
 221,
 3065,
 221

In [26]:
token_ids

[36,
 264,
 263,
 221,
 1019,
 286,
 12,
 221,
 6291,
 221,
 2286,
 221,
 650,
 4033,
 221,
 8388,
 221,
 294,
 221,
 744,
 221,
 1069,
 21809,
 221,
 282,
 221,
 3065,
 221,
 1019,
 286,
 12,
 221,
 878,
 314,
 221,
 1019,
 286,
 221,
 2736,
 9325,
 221,
 1556,
 314,
 221,
 1874,
 382,
 265,
 221,
 294,
 221,
 4225,
 315,
 14,
 221,
 36,
 264,
 263,
 221,
 1019,
 286,
 12,
 221,
 878,
 9369,
 221,
 1019,
 286,
 529,
 221,
 3356,
 221,
 356,
 347,
 12,
 221,
 560,
 221,
 5645,
 305,
 221,
 4405,
 221,
 613,
 2664,
 221,
 588,
 628,
 221,
 6830,
 221,
 294,
 221,
 6176,
 221,
 6724,
 221,
 579,
 45682,
 317,
 221,
 282,
 221,
 3065,
 221,
 1019,
 286,
 12,
 221,
 878,
 2617,
 221,
 374,
 221,
 949,
 17987,
 221,
 3410,
 221,
 6255,
 331,
 221,
 8456,
 221,
 1611,
 289,
 221,
 42921,
 278,
 221,
 10171,
 73,
 221,
 319,
 221,
 528,
 221,
 491,
 21809,
 14,
 221,
 36,
 264,
 263,
 221,
 1019,
 286,
 12,
 221,
 2647,
 221,
 2725,
 521,
 221,
 351,
 1465,
 221,
 1462,
 12,
 221,
 3065,
 221

In [27]:
import torch
a = torch.tensor(token_ids)

In [28]:
context_length = 12
stride = 2

In [29]:
from koRKut_dataloader import TextDataset
korkut_dataloader = TextDataset(token_ids=a, context_length=context_length, stride=stride)
korkut_dataloader.inputs[0], korkut_dataloader.targets[0]

(tensor([  36,  264,  263,  221, 1019,  286,   12,  221, 6291,  221, 2286,  221]),
 tensor([ 264,  263,  221, 1019,  286,   12,  221, 6291,  221, 2286,  221,  650]))

In [30]:
tokenizer.vocab_size

50257

In [32]:
from koRKut_model import koRKutModel

korkut_model = koRKutModel(vocab_size=tokenizer.vocab_size, embedding_dim=16, num_heads=4, context_length=12, num_layers=2, device=device)

In [33]:
import torch
optimizer = torch.optim.Adam(korkut_model.parameters(), lr=1e-3)
loss_fn = torch.nn.CrossEntropyLoss()

In [ ]:
from koRKut_train import koRKutTrain

trainer = koRKutTrain(korkut_model, korkut_dataloader, optimizer, loss_fn, device=device)
trainer.train(epochs=100)

In [ ]:
# the capital of the united states is not london.
sentence = "Derin öğrenme"
sentence_token = tokenizer.encode(sentence)
sentence_token

[28532, 259, 6184, 114, 33133, 918, 1326]

In [ ]:
b = torch.tensor(sentence_token)

In [ ]:
korkut_model.eval()
out = korkut_model.generate(b, max_new_tokens=10)
out

[28532,
 259,
 6184,
 114,
 33133,
 918,
 1326,
 390,
 33133,
 918,
 1326,
 11,
 6184,
 114,
 33133,
 918,
 1326]

In [ ]:
tokenizer.decode(out)

'Derin öğrenme değrenme, öğrenme'